# spring.application.name=demo

# PostgreSQL接続設定
spring.datasource.url=jdbc:postgresql://localhost:5432/work_db
spring.datasource.username=user
spring.datasource.password=password

# JPA
spring.jpa.hibernate.ddl-auto=none

# SQLログ表示
spring.jpa.show-sql=true

jwt.secret=0123456789ABCDEF0123456789ABCDEF